name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


env:
  NODE_VER: 18

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}

      - name: Install
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build

   
